// Renders docs/generated/catalog-schema.md from the schema, so the doc can't drift from the code.
import { SCHEMA_SQL, SCHEMA_VERSION } from '../../server/catalog/schema.ts';

export function renderSchemaDoc(): string {
  return [
    '# Catalog schema',
    '',
    `Generated by \`npm run catalog:build\` from \`server/catalog/schema.ts\` (schema version ${SCHEMA_VERSION}). Don't edit it by hand: change the schema file and rebuild.`,
    '',
    'Why the catalog has this shape: the [catalog design doc](../design-docs/catalog.md).',
    '',
    '```sql',
    SCHEMA_SQL.trimEnd(),
    '```',
    '',
  ].join('\n');
}
